spring:
  application:
    name: journal-service
  data:
    mongodb:
      uri: mongodb+srv://mongodb:MbOqRs7rjgW7UC9Q@cluster0.grc91rj.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true
server:
  port: 8081
